# -*- coding: utf-8 -*-
"""Python 2211CS020178.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ec77-7iUClG48H10US7s1z93m5YwI8U
"""

list=['hello','hi']
print(list)  #hetrogenus elements and indexing mutable and tuple is immutable list operations + and * concatenation and repeat

list = ['19','20']
print(list)

list1 = ['39','40','hello','hi']
print(list1)

hello = ['a','b','c','d','e','f']
hello[1:3]

hello[:4]

hello[:]

hello[1:3]=['x','y']
print(hello)

age=['23','34','35']
studyhrs=['4','5','6']
marks=['67','78','89']
print(age[1],studyhrs[1],marks[1])